const nameLinks = {
    "axel la pira": ["Test", "Successful"],
    "zoe gordon": ["Hi Zoe","I hope this website will work"],
    "lauren-ava carey": ["Elliot Francolla (elliot.francolla@sjc.ox.ac.uk)", "Cameron Deol (cameron.deol@sjc.ox.ac.uk)"],
    "ava carey": ["Elliot Francolla (elliot.francolla@sjc.ox.ac.uk)", "Cameron Deol (cameron.deol@sjc.ox.ac.uk)"],
    "lauren carey": ["Elliot Francolla (elliot.francolla@sjc.ox.ac.uk)", "Cameron Deol (cameron.deol@sjc.ox.ac.uk)"],
    "anwyn ramsey": ["Carl Peck (carl.peck@sjc.ox.ac.uk)", "Zohaib Bhatti (zohaib.bhatti@sjc.ox.ac.uk)"],
    "robbie moustafa": ["Elena Radulova (elena.radulova@sjc.ox.ac.uk)", "Saskia Abou-khater Robbiati (saskia.abou-khaterrobbiati@sjc.ox.ac.uk)"],
    "sofia o'casey": ["Akarsh Shankar (akarsh.shankar@sjc.ox.ac.uk)", "Sehar Ahmed (sehar.ahmed@sjc.ox.ac.uk)"],
    "juliet taub": ["Libby Rock (libby.rock@sjc.ox.ac.uk)", "Oscar Fitzgerald (oscar.fitzgerald@sjc.ox.ac.uk)"],
    "tia westwood": ["Gabrielle Drutchas (gabrielle.drutchas@sjc.ox.ac.uk)", "Charlotte Ross (charlotte.ross@sjc.ox.ac.uk)"],
    "zain ahmed khan": ["Mel Morley (melissa.morley@sjc.ox.ac.uk)", "Rebecca Durham (rebecca.durham@sjc.ox.ac.uk)"],
    "zain khan": ["Mel Morley (melissa.morley@sjc.ox.ac.uk)", "Rebecca Durham (rebecca.durham@sjc.ox.ac.uk)"],
    "jack leo yan pentland": ["Kailin Guo (kailin.guo@sjc.ox.ac.uk)", "Euan Warner (euan.warner@sjc.ox.ac.uk)", "Amelia Taylor (amelia.taylor@sjc.ox.ac.uk)"],
    "jack pentland": ["Kailin Guo (kailin.guo@sjc.ox.ac.uk)", "Euan Warner (euan.warner@sjc.ox.ac.uk)", "Amelia Taylor (amelia.taylor@sjc.ox.ac.uk)"],
    "jack yan pentland": ["Kailin Guo (kailin.guo@sjc.ox.ac.uk)", "Euan Warner (euan.warner@sjc.ox.ac.uk)", "Amelia Taylor (amelia.taylor@sjc.ox.ac.uk)"],
    "nathan symons": ["Zoe Gordon (zoe.gordon@sjc.ox.ac.uk)", "Noah Cartwright (noah.cartwright@sjc.ox.ac.uk)"],
    "ishen dodhia": ["Owen Casstles (owen.casstles@sjc.ox.ac.uk)", "Anna Theobalds (anna.theobalds@sjc.ox.ac.uk)", "Josie Shuall (josephine.shuall@sjc.ox.ac.uk)"],
    "miriam fraser": ["Elsa Reid (elsa.reid@sjc.ox.ac.uk)", "Amy Lawson (amy.lawson@sjc.ox.ac.uk)"],
    "joe hennings": ["Rohan Joshi (rohan.joshi@sjc.ox.ac.uk)", "Cameron Coates (cameron.coates@sjc.ox.ac.uk)"],
    "kate sophie jenneke mitchell": ["Owen Casstles (owen.casstles@sjc.ox.ac.uk)", "Anna Theobalds (anna.theobalds@sjc.ox.ac.uk)", "Josie Shuall (josephine.shuall@sjc.ox.ac.uk)"],
    "kate mitchell": ["Owen Casstles (owen.casstles@sjc.ox.ac.uk)", "Anna Theobalds (anna.theobalds@sjc.ox.ac.uk)", "Josie Shuall (josephine.shuall@sjc.ox.ac.uk)"],
    "madeleine levey": ["Arran Kinnear (arran.kinnear@sjc.ox.ac.uk)", "Ben Smith (benjamin.smith@sjc.ox.ac.uk)", "Leandro Landolina (leandro.landolina@sjc.ox.ac.uk)"],
    "rebecca rendall": ["Axel La Pira (axel.lapira@sjc.ox.ac.uk)", "Benjamin Bull (benjamin.bull@sjc.ox.ac.uk)"],
    "yifei zhou": ["Arran Kinnear (arran.kinnear@sjc.ox.ac.uk)", "Ben Smith (benjamin.smith@sjc.ox.ac.uk)", "Leandro Landolina (leandro.landolina@sjc.ox.ac.uk)"],
    "tom blackburn": ["Owen Casstles (owen.casstles@sjc.ox.ac.uk)", "Anna Theobalds (anna.theobalds@sjc.ox.ac.uk)", "Josie Shuall (josephine.shuall@sjc.ox.ac.uk)"],
    "rory katherine dean": ["Owen Casstles (owen.casstles@sjc.ox.ac.uk)", "Anna Theobalds (anna.theobalds@sjc.ox.ac.uk)", "Josie Shuall (josephine.shuall@sjc.ox.ac.uk)"],
    "rory dean": ["Owen Casstles (owen.casstles@sjc.ox.ac.uk)", "Anna Theobalds (anna.theobalds@sjc.ox.ac.uk)", "Josie Shuall (josephine.shuall@sjc.ox.ac.uk)"],
    "isaac thomas harold funk": ["Ewan Kane (ewangkane17@gmail.com)"],
    "isaac funk": ["Ewan Kane (ewangkane17@gmail.com)"],
    "marina harrison": ["Rahima Ahmed (rahima.ahmed@sjc.ox.ac.uk)", "Christopher Liu (christopher.liu@sjc.ox.ac.uk)"],
    "peter kovacs": ["Mark Oravecz (mark.oravecz@sjc.ox.ac.uk)", "Alexander Prvulovich (alexander.prvulovich@sjc.ox.ac.uk)"],
    "albert li": ["Ewan Kane (ewangkane17@gmail.com)"],
    "xingjian li": ["Ewan Kane (ewangkane17@gmail.com)"],
    "xingjian/albert li": ["Ewan Kane (ewangkane17@gmail.com)"],
    "cameron noble": ["Mark Oravecz (mark.oravecz@sjc.ox.ac.uk)", "Alexander Prvulovich (alexander.prvulovich@sjc.ox.ac.uk)"],
    "dylan o'neill": ["Maxime Atkinson (maxime.atkinson@sjc.ox.ac.uk)", "Sofia Tagliani Beltrán (sofia.taglianibeltran@sjc.ox.ac.uk)"],
    "karina mae oakley": ["Elena Radulova (elena.radulova@sjc.ox.ac.uk)", "Saskia Abou-khater Robbiati (saskia.abou-khaterrobbiati@sjc.ox.ac.uk)"],
    "karina oakley": ["Elena Radulova (elena.radulova@sjc.ox.ac.uk)", "Saskia Abou-khater Robbiati (saskia.abou-khaterrobbiati@sjc.ox.ac.uk)"],
    "tanaquil lu lu/qizhang lu": ["Alice Minihane (alice.minihane@sjc.ox.ac.uk)", "Laura Brownlow (laura.brownlow@sjc.ox.ac.uk)", "Kaya Yarde (kaya.yarde@sjc.ox.ac.uk)"],
    "qizhang lu": ["Alice Minihane (alice.minihane@sjc.ox.ac.uk)", "Laura Brownlow (laura.brownlow@sjc.ox.ac.uk)", "Kaya Yarde (kaya.yarde@sjc.ox.ac.uk)"],
    "tanaquil lu": ["Alice Minihane (alice.minihane@sjc.ox.ac.uk)", "Laura Brownlow (laura.brownlow@sjc.ox.ac.uk)", "Kaya Yarde (kaya.yarde@sjc.ox.ac.uk)"],
    "tanaquil lu lu": ["Alice Minihane (alice.minihane@sjc.ox.ac.uk)", "Laura Brownlow (laura.brownlow@sjc.ox.ac.uk)", "Kaya Yarde (kaya.yarde@sjc.ox.ac.uk)"],
    "shlok venkat": ["Alice Minihane (alice.minihane@sjc.ox.ac.uk)", "Laura Brownlow (laura.brownlow@sjc.ox.ac.uk)", "Kaya Yarde (kaya.yarde@sjc.ox.ac.uk)"],
    "cosima yeo": ["Amy Lawson (amy.lawson@sjc.ox.ac.uk)", "Elsa Reid (elsa.reid@sjc.ox.ac.uk)"],
    "saron ghebremeskel": ["Carmen Omitowoju (carmen.omitowoju@sjc.ox.ac.uk)"],
    "james kramer": ["Carmen Omitowoju (carmen.omitowoju@sjc.ox.ac.uk)"],
    "james harper-jones": ["Elena Radulova (elena.radulova@sjc.ox.ac.uk)", "Saskia Abou-khater Robbiati (saskia.abou-khaterrobbiati@sjc.ox.ac.uk)"],
    "andras bard": ["Arran Kinnear (arran.kinnear@sjc.ox.ac.uk)", "Ben Smith (benjamin.smith@sjc.ox.ac.uk)", "Leandro Landolina (leandro.landolina@sjc.ox.ac.uk)"],
    "cyrus/sin l chan": ["Yangchen Guan (yangchen.guan@sjc.ox.ac.uk)", "Burak Karatas (burak.karatas@sjc.ox.ac.uk)"],
    "cyrus l chan": ["Yangchen Guan (yangchen.guan@sjc.ox.ac.uk)", "Burak Karatas (burak.karatas@sjc.ox.ac.uk)"],
    "sin l chan": ["Yangchen Guan (yangchen.guan@sjc.ox.ac.uk)", "Burak Karatas (burak.karatas@sjc.ox.ac.uk)"],
    "cyrus chan": ["Yangchen Guan (yangchen.guan@sjc.ox.ac.uk)", "Burak Karatas (burak.karatas@sjc.ox.ac.uk)"],
    "sin chan": ["Yangchen Guan (yangchen.guan@sjc.ox.ac.uk)", "Burak Karatas (burak.karatas@sjc.ox.ac.uk)"],
    "ellie mccartney": ["Axel La Pira (axel.lapira@sjc.ox.ac.uk)", "Benjamin Bull (Sjoh5901@ox.ac.uk)"],
    "david richter": ["Gareth Tan (Sjoh5803@ox.ac.uk)", "Henry Field (Sjoh5811@ox.ac.uk)"],
    "alex cook": ["Edmund Hall (edmund.hall@sjc.ox.ac.uk)", "Mia Hewitt (mia.hewitt@sjc.ox.ac.uk)"],
    "uma eliza eickelberg": ["Edmund Hall (edmund.hall@sjc.ox.ac.uk)", "Mia Hewitt (mia.hewitt@sjc.ox.ac.uk)"],
    "uma eickelberg": ["Edmund Hall (edmund.hall@sjc.ox.ac.uk)", "Mia Hewitt (mia.hewitt@sjc.ox.ac.uk)"],
    "yuheng fu": ["Rahima Ahmed (rahima.ahmed@sjc.ox.ac.uk)", "Christopher Liu (christopher.liu@sjc.ox.ac.uk)"],
    "ben hone": ["Josh Ejovi (joshua.ejovi@sjc.ox.ac.uk)"],
    "sarah murphy": ["Diego Danese (diego.danese@sjc.ox.ac.uk)"],
    "alec springford": ["Diego Danese (diego.danese@sjc.ox.ac.uk)"],
    "noah trane trane": ["Zaheen A-Rahman (zaheen.a-rahman@sjc.ox.ac.uk)"],
    "noah trane": ["Zaheen A-Rahman (zaheen.a-rahman@sjc.ox.ac.uk)"],
    "isabel elsner": ["Emily Doughty (emily.doughty@sjc.ox.ac.uk)", "Ava Chadderton (ava.chadderton@sjc.ox.ac.uk)"],
    "inaya chaudhry": ["Zuzanna Wagrowska (zuzanna.wagrowska@sjc.ox.ac.uk)", "Tegan Addison (tegan.addison@sjc.ox.ac.uk)", "Liv Goldreich (liv.goldreich@sjc.ox.ac.uk)"],
    "samuel cowling": ["Emma Scanlon (emma.scanlon@sjc.ox.ac.uk)", "Georgina Cooper (georgina.cooper@sjc.ox.ac.uk)", "Katie Skilling (katie.skilling@sjc.ox.ac.uk)", "Emily Gurney (emily.gurney@sjc.ox.ac.uk)"],
    "daniel cunningham": ["Tom Henderson (tom.henderson@sjc.ox.ac.uk)", "Toby Kennedy (toby.kennedy@sjc.ox.ac.uk)"],
    "daphne anna sophie morris": ["Alice Dunn (alice.dunn@sjc.ox.ac.uk)", "Declan Collins (declan.collins@sjc.ox.ac.uk)"],
    "daphne morris": ["Alice Dunn (alice.dunn@sjc.ox.ac.uk)", "Declan Collins (declan.collins@sjc.ox.ac.uk)"],
    "patrick rabey": ["Zuzanna Wagrowska (zuzanna.wagrowska@sjc.ox.ac.uk)", "Tegan Addison (tegan.addison@sjc.ox.ac.uk)", "Liv Goldreich (liv.goldreich@sjc.ox.ac.uk)"],
    "amelia bateson": ["Maxime Atkinson (maxime.atkinson@sjc.ox.ac.uk)", "Sofía Tagliani Beltrán (sofia.taglianibeltran@sjc.ox.ac.uk)"],
    "xinyuan ma": ["Emily Doughty (emily.doughty@sjc.ox.ac.uk)", "Ava Chadderton (ava.chadderton@sjc.ox.ac.uk)"],
    "ella lee": ["Sanaya Narula (sanaya.narula@sjc.ox.ac.uk)", "Hasina Ibrahim (hasina.ibrahim@sjc.ox.ac.uk)"],
    "florence dobney": ["Alice Dunn (alice.dunn@sjc.ox.ac.uk)", "Declan Collins (declan.collins@sjc.ox.ac.uk)"],
    "jerome nicholas pailing": ["Freya Ashworth (freya.ashworth@sjc.ox.ac.uk)", "Karishma Lehto (karishma.lehto@sjc.ox.ac.uk)"],
    "jerome pailing": ["Freya Ashworth (freya.ashworth@sjc.ox.ac.uk)", "Karishma Lehto (karishma.lehto@sjc.ox.ac.uk)"],
    "mahnoor kamran": ["Sanaya Narula (sanaya.narula@sjc.ox.ac.uk)", "Hasina Ibrahim (hasina.ibrahim@sjc.ox.ac.uk)"],
    "julia melody fiona marshall": ["Sanaya Narula (sanaya.narula@sjc.ox.ac.uk)", "Hasina Ibrahim (hasina.ibrahim@sjc.ox.ac.uk)"],
    "julia marshall": ["Sanaya Narula (sanaya.narula@sjc.ox.ac.uk)", "Hasina Ibrahim (hasina.ibrahim@sjc.ox.ac.uk)"],
    "nimrod morwood": ["Owen Casstles (owen.casstles@sjc.ox.ac.uk)", "Anna Theobalds (anna.theobalds@sjc.ox.ac.uk)", "Josie Shuall (josephine.shuall@sjc.ox.ac.uk)"],
    "emily valerie saunders": ["Patrick Ashmore (patrick.ashmore@sjc.ox.ac.uk)", "Philip Nedelev (philip.nedelev@sjc.ox.ac.uk)", "Nikola Lakic (nikola.lakic@sjc.ox.ac.uk)"],
    "emily saunders": ["Patrick Ashmore (patrick.ashmore@sjc.ox.ac.uk)", "Philip Nedelev (philip.nedelev@sjc.ox.ac.uk)", "Nikola Lakic (nikola.lakic@sjc.ox.ac.uk)"],
    "ewan gatenby": ["Edmund Hall (edmund.hall@sjc.ox.ac.uk)", "Mia Hewitt (mia.hewitt@sjc.ox.ac.uk)"],
    "milo man": ["Freya Ashworth (freya.ashworth@sjc.ox.ac.uk)", "Karishma Lehto (karishma.lehto@sjc.ox.ac.uk)"],
    "milo nathaniel man": ["Freya Ashworth (freya.ashworth@sjc.ox.ac.uk)", "Karishma Lehto (karishma.lehto@sjc.ox.ac.uk)"],
    "ewan plowden-wardlaw": ["Amy Lawson (amy.lawson@sjc.ox.ac.uk)", "Elsa Reid (elsa.reid@sjc.ox.ac.uk)"],
    "ariene alexandra horner": ["Mel Morley (melissa.morley@sjc.ox.ac.uk)", "Rebecca Durham (rebecca.durham@sjc.ox.ac.uk)"],
    "ariene horner": ["Mel Morley (melissa.morley@sjc.ox.ac.uk)", "Rebecca Durham (rebecca.durham@sjc.ox.ac.uk)"],
    "otto johnson": ["Joe Dunn (joe.dunn@sjc.ox.ac.uk)", "Richard Garrard (richard.garrard@sjc.ox.ac.uk)"],
    "katie pannick": ["Elliot Francolla (elliot.francolla@sjc.ox.ac.uk)", "Cameron Deol (cameron.deol@sjc.ox.ac.uk)"],
    "louise smith": ["Elliot Francolla (elliot.francolla@sjc.ox.ac.uk)", "Cameron Deol (cameron.deol@sjc.ox.ac.uk)"],
    "clementine thorpe": ["Mel Morley (melissa.morley@sjc.ox.ac.uk)", "Rebecca Durham (rebecca.durham@sjc.ox.ac.uk)"],
    "maxim anatolievich vorobev": ["Tom Henderson (tom.henderson@sjc.ox.ac.uk)", "Toby Kennedy (toby.kennedy@sjc.ox.ac.uk)"],
    "maxim vorobev": ["Tom Henderson (tom.henderson@sjc.ox.ac.uk)", "Toby Kennedy (toby.kennedy@sjc.ox.ac.uk)"],
    "rhythm dhir": ["Isabel Williamson (isabel.williamson@sjc.ox.ac.uk)", "Lilia Goldstein (lilia.goldstein@sjc.ox.ac.uk)"],
    "guilherme lopes": ["Isabel Williamson (isabel.williamson@sjc.ox.ac.uk)", "Lilia Goldstein (lilia.goldstein@sjc.ox.ac.uk)"],
    "hannah fareed": ["Oscar Whittle (oscar.whittle@sjc.ox.ac.uk)", "Job Estill (job.estill@sjc.ox.ac.uk)"],
    "merit habib matta": ["Kailin Guo (kailin.guo@sjc.ox.ac.uk)", "Euan Warner (euan.warner@sjc.ox.ac.uk)", "Amelia Taylor (amelia.taylor@sjc.ox.ac.uk)"],
    "merit matta": ["Kailin Guo (kailin.guo@sjc.ox.ac.uk)", "Euan Warner (euan.warner@sjc.ox.ac.uk)", "Amelia Taylor (amelia.taylor@sjc.ox.ac.uk)"],
    "emily dodds": ["Oscar Whittle (oscar.whittle@sjc.ox.ac.uk)", "Job Estill (job.estill@sjc.ox.ac.uk)"],
    "naomi armstrong": ["Isabel Gregory (isabel.gregory@sjc.ox.ac.uk)", "Samuel Dayan (sjoh5840@ox.ac.uk)"],
    "xin yi ho": ["Emily Doughty (emily.doughty@sjc.ox.ac.uk)", "Ava Chadderton (ava.chadderton@sjc.ox.ac.uk)"],
    "xin ho": ["Emily Doughty (emily.doughty@sjc.ox.ac.uk)", "Ava Chadderton (ava.chadderton@sjc.ox.ac.uk)"],
    "jacopo congiu-hughes": ["Alfred Emmott (alfred.emmott@sjc.ox.ac.uk)", "Joseph Munn (joseph.munn@sjc.ox.ac.uk)"],
    "lia rose kishori jobanputra": ["Zanita Yuen (zanita.yuen@sjc.ox.ac.uk)", "Dylan Knight (dylan.knight@sjc.ox.ac.uk)"],
    "lia jobanputra": ["Zanita Yuen (zanita.yuen@sjc.ox.ac.uk)", "Dylan Knight (dylan.knight@sjc.ox.ac.uk)"],
    "lia kishori jobanputra": ["Zanita Yuen (zanita.yuen@sjc.ox.ac.uk)", "Dylan Knight (dylan.knight@sjc.ox.ac.uk)"],
    "lydia ojeyemi": ["Emma Scanlon (emma.scanlon@sjc.ox.ac.uk)", "Georgina Cooper (georgina.cooper@sjc.ox.ac.uk)", "Katie Skilling (katie.skilling@sjc.ox.ac.uk)", "Emily Gurney (emily.gurney@sjc.ox.ac.uk)"],
    "deborah akinsanya": ["Libertad Seoane de la Fuente (libertad.seoanedelafuente@sjc.ox.ac.uk)", "Zi Ning Lau (zining.lau@sjc.ox.ac.uk)", "Cameron Setiadi (cameron.setiadi@sjc.ox.ac.uk)"],
    "maya flint": ["Libertad Seoane de la Fuente (libertad.seoanedelafuente@sjc.ox.ac.uk)", "Zi Ning Lau (zining.lau@sjc.ox.ac.uk)", "Cameron Setiadi (cameron.setiadi@sjc.ox.ac.uk)"],
    "emma king": ["Gareth Tan (Sjoh5803@ox.ac.uk)", "Henry Field (Sjoh5811@ox.ac.uk)"],
    "jessica nisha williamson": ["Libertad Seoane de la Fuente (libertad.seoanedelafuente@sjc.ox.ac.uk)", "Zi Ning Lau (zining.lau@sjc.ox.ac.uk)", "Cameron Setiadi (cameron.setiadi@sjc.ox.ac.uk)"],
    "jessica williamson": ["Libertad Seoane de la Fuente (libertad.seoanedelafuente@sjc.ox.ac.uk)", "Zi Ning Lau (zining.lau@sjc.ox.ac.uk)", "Cameron Setiadi (cameron.setiadi@sjc.ox.ac.uk)"],
    "jessica young": ["Patrick Ashmore (patrick.ashmore@sjc.ox.ac.uk)", "Philip Nedelev (philip.nedelev@sjc.ox.ac.uk)", "Nikola Lakic (nikola.lakic@sjc.ox.ac.uk)"],
    "ciara brady": ["Melanie Henin (melanie.henin@sjc.ox.ac.uk)", "Claire Yao (claire.yao@sjc.ox.ac.uk)"],
    "philip kimber": ["Oliver Butcher (oliver.butcher@sjc.ox.ac.uk)", "Eric He (fengming.he@sjc.ox.ac.uk)", "Joseph Leach (joseph.leach@sjc.ox.ac.uk)"],
    "anna mackinnon": ["Libertad Seoane de la Fuente (libertad.seoanedelafuente@sjc.ox.ac.uk)", "Zi Ning Lau (zining.lau@sjc.ox.ac.uk)", "Cameron Setiadi (cameron.setiadi@sjc.ox.ac.uk)"],
    "rushil mathur": ["Carl Peck (sjoh5746@ox.ac.uk)", "Zohaib Bhatti (zohaib.bhatti@sjc.ox.ac.uk)"],
    "freddie weir": ["Alex Mylet (alexander.mylet@sjc.ox.ac.uk)", "Athavan Arulalagan (athavan.arulalagan@sjc.ox.ac.uk)"],
    "ishaan das": ["Yangchen Guan (yangchen.guan@sjc.ox.ac.uk)", "Burak Karatas (burak.karatas@sjc.ox.ac.uk)"],
    "rowan harrison-walker": ["Zanita Yuen (zanita.yuen@sjc.ox.ac.uk)", "Dylan Knight (dylan.knight@sjc.ox.ac.uk)"],
    "gvozden lapcevic": ["Oliver Butcher (oliver.butcher@sjc.ox.ac.uk)", "Eric He (fengming.he@sjc.ox.ac.uk)", "Joseph Leach (joseph.leach@sjc.ox.ac.uk)"],
    "frederick li": ["Oliver Butcher (oliver.butcher@sjc.ox.ac.uk)", "Eric He (fengming.he@sjc.ox.ac.uk)", "Joseph Leach (joseph.leach@sjc.ox.ac.uk)"],
    "chao ren": ["Carl Peck (sjoh5746@ox.ac.uk)", "Zohaib Bhatti (zohaib.bhatti@sjc.ox.ac.uk)"],
    "tanupat trakulthongchai": ["Meira Lee (meira.lee@sjc.ox.ac.uk)", "Ziji Lee (ziji.lee@sjc.ox.ac.uk)"],
    "joyce/yueming wang": ["Melanie Henin (melanie.henin@sjc.ox.ac.uk)", "Claire Yao (claire.yao@sjc.ox.ac.uk)"],
    "joyce wang": ["Melanie Henin (melanie.henin@sjc.ox.ac.uk)", "Claire Yao (claire.yao@sjc.ox.ac.uk)"],
    "yueming wang": ["Melanie Henin (melanie.henin@sjc.ox.ac.uk)", "Claire Yao (claire.yao@sjc.ox.ac.uk)"],
    "kilian pschierer": ["Yangchen Guan (yangchen.guan@sjc.ox.ac.uk)", "Burak Karatas (burak.karatas@sjc.ox.ac.uk)"],
    "arnav agarwal": ["Isabel Gregory (isabel.gregory@sjc.ox.ac.uk)", "Samuel Dayan (sjoh5840@ox.ac.uk)"],
    "leanne mabena": ["Mel Morley (melissa.morley@sjc.ox.ac.uk)", "Rebecca Durham (rebecca.durham@sjc.ox.ac.uk)"],
    "anya macaulay": ["Zoe Gordon (zoe.gordon@sjc.ox.ac.uk)", "Noah Cartwright (noah.cartwright@sjc.ox.ac.uk)"],
    "niorla nimal": ["Freya Ashworth (freya.ashworth@sjc.ox.ac.uk)", "Karishma Lehto (karishma.lehto@sjc.ox.ac.uk)"],
    "ian matthew sun": ["Alex Mylet (alexander.mylet@sjc.ox.ac.uk)", "Athavan Arulalagan (athavan.arulalagan@sjc.ox.ac.uk)"],
    "bo/maisie yeates": ["Agata Bakalorz (agata.bakalorz@sjc.ox.ac.uk)", "Jamie Warren (jamie.warren@sjc.ox.ac.uk)"],
    "nicole maria palka": ["Zuzanna Wagrowska (zuzanna.wagrowska@sjc.ox.ac.uk)", "Tegan Addison (tegan.addison@sjc.ox.ac.uk)", "Liv Goldreich (liv.goldreich@sjc.ox.ac.uk)"],
    "nicole palka": ["Zuzanna Wagrowska (zuzanna.wagrowska@sjc.ox.ac.uk)", "Tegan Addison (tegan.addison@sjc.ox.ac.uk)", "Liv Goldreich (liv.goldreich@sjc.ox.ac.uk)"],
    "elliot wigham": ["Arran Kinnear (arran.kinnear@sjc.ox.ac.uk)", "Ben Smith (benjamin.smith@sjc.ox.ac.uk)", "Leandro Landolina (leandro.landolina@sjc.ox.ac.uk)"],
    "dara a t moh'd": ["Agata Bakalorz (agata.bakalorz@sjc.ox.ac.uk)", "Jamie Warren (jamie.warren@sjc.ox.ac.uk)"],
    "dara a t mohd": ["Agata Bakalorz (agata.bakalorz@sjc.ox.ac.uk)", "Jamie Warren (jamie.warren@sjc.ox.ac.uk)"],
    "dara moh'd": ["Agata Bakalorz (agata.bakalorz@sjc.ox.ac.uk)", "Jamie Warren (jamie.warren@sjc.ox.ac.uk)"],
    "dara mohd": ["Agata Bakalorz (agata.bakalorz@sjc.ox.ac.uk)", "Jamie Warren (jamie.warren@sjc.ox.ac.uk)"],
    "qasim ahmad": ["Alfred Emmott (alfred.emmott@sjc.ox.ac.uk)", "Joseph Munn (joseph.munn@sjc.ox.ac.uk)"],
    "theo cunningham": ["Alexander Prvulovich (alexander.prvulovich@sjc.ox.ac.uk)", "Mark Oravecz (mark.oravecz@sjc.ox.ac.uk)"],
    "amelia jolly": ["Meira Lee (meira.lee@sjc.ox.ac.uk)", "Ziji Lee (ziji.lee@sjc.ox.ac.uk)"],
    "zoe lui": ["Alice Minihane (alice.minihane@sjc.ox.ac.uk)", "Laura Brownlow (laura.brownlow@sjc.ox.ac.uk)", "Kaya Yarde (kaya.yarde@sjc.ox.ac.uk)"],
    "charlotte rose goodchild": ["Emma Scanlon (emma.scanlon@sjc.ox.ac.uk)", "Georgina Cooper (georgina.cooper@sjc.ox.ac.uk)", "Katie Skilling (katie.skilling@sjc.ox.ac.uk)", "Emily Gurney (emily.gurney@sjc.ox.ac.uk)"],
    "charlotte goodchild": ["Emma Scanlon (emma.scanlon@sjc.ox.ac.uk)", "Georgina Cooper (georgina.cooper@sjc.ox.ac.uk)", "Katie Skilling (katie.skilling@sjc.ox.ac.uk)", "Emily Gurney (emily.gurney@sjc.ox.ac.uk)"],
    "catherine isla hayton": ["Xander Cooke (alexander.cooke@sjc.ox.ac.uk)", "Laurence Cooke (laurence.cooke@sjc.ox.ac.uk)"],
    "catherine hayton": ["Xander Cooke (alexander.cooke@sjc.ox.ac.uk)", "Laurence Cooke (laurence.cooke@sjc.ox.ac.uk)"],
    "joan pau jaen mendoza": ["Emma Scanlon (emma.scanlon@sjc.ox.ac.uk)", "Georgina Cooper (georgina.cooper@sjc.ox.ac.uk)", "Katie Skilling (katie.skilling@sjc.ox.ac.uk)", "Emily Gurney (emily.gurney@sjc.ox.ac.uk)"],
    "joan mendoza": ["Emma Scanlon (emma.scanlon@sjc.ox.ac.uk)", "Georgina Cooper (georgina.cooper@sjc.ox.ac.uk)", "Katie Skilling (katie.skilling@sjc.ox.ac.uk)", "Emily Gurney (emily.gurney@sjc.ox.ac.uk)"],
    "joan jaen mendoza": ["Emma Scanlon (emma.scanlon@sjc.ox.ac.uk)", "Georgina Cooper (georgina.cooper@sjc.ox.ac.uk)", "Katie Skilling (katie.skilling@sjc.ox.ac.uk)", "Emily Gurney (emily.gurney@sjc.ox.ac.uk)"],
    "joan pau mendoza": ["Emma Scanlon (emma.scanlon@sjc.ox.ac.uk)", "Georgina Cooper (georgina.cooper@sjc.ox.ac.uk)", "Katie Skilling (katie.skilling@sjc.ox.ac.uk)", "Emily Gurney (emily.gurney@sjc.ox.ac.uk)"],
    "arda kurtoglu": ["Xander Cooke (alexander.cooke@sjc.ox.ac.uk)", "Laurence Cooke (laurence.cooke@sjc.ox.ac.uk)"],
    "vishal mohanty": ["Patrick Ashmore (patrick.ashmore@sjc.ox.ac.uk)", "Philip Nedelev (philip.nedelev@sjc.ox.ac.uk)", "Nikola Lakic (nikola.lakic@sjc.ox.ac.uk)"],
    "trace/zichi zhang": ["Rohan Joshi (rohan.joshi@sjc.ox.ac.uk)", "Cameron Coates (cameron.coates@sjc.ox.ac.uk)"],
    "trace zhang": ["Rohan Joshi (rohan.joshi@sjc.ox.ac.uk)", "Cameron Coates (cameron.coates@sjc.ox.ac.uk)"],
    "zichi zhang": ["Rohan Joshi (rohan.joshi@sjc.ox.ac.uk)", "Cameron Coates (cameron.coates@sjc.ox.ac.uk)"],
    "konstanti rumiantsev": ["Akarsh Shankar (akarsh.shankar@sjc.ox.ac.uk)", "Sehar Ahmed (sehar.ahmed@sjc.ox.ac.uk)"],
    "ryan teo": ["Alfred Emmott (alfred.emmott@sjc.ox.ac.uk)", "Joseph Munn (joseph.munn@sjc.ox.ac.uk)"],
    "sofya donets": ["Axel La Pira (axel.lapira@sjc.ox.ac.uk)", "Benjamin Bull (Sjoh5901@ox.ac.uk)"],
    "ruth magedera": ["Maxime Atkinson (maxime.atkinson@sjc.ox.ac.uk)", "Sofía Tagliani Beltrán (sofia.taglianibeltran@sjc.ox.ac.uk)"],
    "sammah fadalla": ["Gareth Tan (sjoh5803@ox.ac.uk)", "Henry Field (sjoh5811@ox.ac.uk)"],
    "grace steed": ["Libby Rock (libby.rock@sjc.ox.ac.uk)", "Oscar Fitzgerald (oscar.fitzgerald@sjc.ox.ac.uk)"],
    "gabriel warley": ["Joe Dunn (joe.dunn@sjc.ox.ac.uk)", "Richard Garrard (richard.garrard@sjc.ox.ac.uk)"]
};


document.getElementById('nameForm').addEventListener('submit', function(event) {
    event.preventDefault();
    
    const nameInput = document.getElementById('nameInput').value.trim().toLowerCase();
    const output = document.getElementById('output');
    
    if (nameLinks[nameInput]) {
        output.textContent = `parents: ${nameLinks[nameInput].join(', ')}`;
    } else {
        output.textContent = 'You have no college parents linked under that name! Check the spelling or if you think there has been a mistake, dont hesistate to email Welfare at jcr-welfare@sjc.ox.ac.uk';
    }
});
